<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203174152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE apartment ADD category_id INT NOT NULL');
        $this->addSql('ALTER TABLE apartment ADD CONSTRAINT FK_4D7E685412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_4D7E685412469DE2 ON apartment (category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE category');
        $this->addSql('ALTER TABLE apartment DROP CONSTRAINT FK_4D7E685412469DE2');
        $this->addSql('DROP INDEX IDX_4D7E685412469DE2');
        $this->addSql('ALTER TABLE apartment DROP category_id');
    }
}
